### ISSUE TITLE
TS-Build has semantic error - requiresClaim

### ISSUE THREAD

**Issue by zimoony** [essential-projects/iam#2]
#### Describe your issue

TS-Build has semantic error at: https://github.com/essential-projects/iam/blob/beb21bdfbacde29e84220b810894cd982f04a566/src/entity_types/user.ts#L6

```
[gulp-typescript] 1238 Unable to resolve signature of class decorator when called as an expression.
  Type 'PropertyDescriptor' is not assignable to type 'void | typeof UserEntity'.
    Type 'PropertyDescriptor' is not assignable to type 'typeof UserEntity'.
      Property 'prototype' is missing in type 'PropertyDescriptor'.
> file: /Users/simonreymann/Entwicklung/process-engine/process_engine_meta/iam/src/entity_types/user.ts:
> [5] @requiresClaim({
> [6]   actions: [
> [7]     [ClaimActionType.all, ['_iam_internal', 'user']],
> [8]   ],
> [9] })
[09:51:55] TypeScript: 1 semantic error
```

#### How can others reproduce the issue?

gulp build

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): OS X
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
Wurde in commit https://github.com/essential-projects/metadata_contracts/commit/08279855eaf900faa3180a71b21eb744d8aef7e6 gefixt
